universe 		= docker
docker_image 		= dankazbek/nnti-2122-project
executable              = mnist.py
output                  = mnist_lenet.$(ClusterId).$(ProcId).ckpt
error                   = out.$(ClusterId).$(ProcId).err
log                     = out.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1
